version: '3'

services:
  waline:
    container_name: waline
    image: lizheming/waline:1.31.12
    restart: always
    ports:
      - 8360:8360
    volumes:
      - ./data:/app/data
    environment:
      - "TZ=Asia/Shanghai"
      - "SQLITE_PATH=/app/data"
      - "JWT_TOKEN=xxxxxxxxxxx"
      - "SITE_NAME=xxxxxxx"
      - "SITE_URL=https://xxxxxxxxxx"
      - "SMTP_SERVICE=163"
      - "SMTP_USER=xxxxxx"
      - "SMTP_PASS=xxxxxxxx"
      - "AUTHOR_EMAIL=xxxxxxx"
      - "SECURE_DOMAINS=xxxxxxxx,xxxxxxxx"
      - "AKISMET_KEY=false"