version: "3"
services: 
  uptime-kuma:
    image: louislam/uptime-kuma:1.11.1
    container_name: "uptime-kuma"
    restart: "always"
    volumes: 
      - "/etc/localtime:/etc/localtime"
      - "./data:/app/data"
    ports: 
      - "80:3001"
